// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShadowViewer.Plugin.Local.Database;

#nullable disable

namespace ShadowViewer.Plugin.Local.Database.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    partial class LocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Cache.CacheImg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ComicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dir")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Md5")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("Path");

                    b.HasKey("Id");

                    b.HasIndex("ComicId");

                    b.ToTable("CacheImg", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Entities.ComicChapter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ComicId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComicId");

                    b.ToTable("ComicChapter", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Entities.ComicDetail", b =>
                {
                    b.Property<long>("ComicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtendId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Folder");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .HasColumnType("TEXT");

                    b.HasKey("ComicId");

                    b.ToTable("ComicDetail", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Entities.ComicNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokenReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBroken")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Folder");

                    b.Property<long>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(-1L);

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePluginDataId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StoredIsFolder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("IsFolder");

                    b.Property<string>("Thumb")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("mx-appx:///default.png");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDateTime")
                        .HasDatabaseName("index_comic_node_created_at");

                    b.HasIndex("Name")
                        .HasDatabaseName("index_comic_node_name");

                    b.HasIndex("NodeType")
                        .HasDatabaseName("index_comic_node_type");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("index_comic_node_parent_id");

                    b.HasIndex("SourcePluginDataId");

                    b.HasIndex("UpdatedDateTime")
                        .HasDatabaseName("index_comic_node_updated_at");

                    b.ToTable("ComicNode", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Entities.ComicPicture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChapterId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ComicId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ComicId");

                    b.ToTable("ComicPicture", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Entities.SourcePluginData", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColorHex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraData")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForegroundColorHex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SourcePluginData", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Models.LocalAuthor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocalAuthor", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Models.LocalComicAuthorMapping", b =>
                {
                    b.Property<long>("ComicId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComicId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("LocalComicAuthorMapping", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Models.LocalComicTagMapping", b =>
                {
                    b.Property<long>("ComicId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ComicId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("LocalComicTagMapping", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Models.LocalHistory", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Extra")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastReadDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumb")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocalHistory", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Models.LocalReadingRecord", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraComicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastEpisode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastPicture")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Percent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocalReadingRecord", (string)null);
                });

            modelBuilder.Entity("ShadowViewer.Sdk.Cache.CacheZip", b =>
                {
                    b.Property<string>("Md5")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha1")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("CachePath")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ComicId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Md5", "Sha1");

                    b.ToTable("CacheZip", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ShadowViewer.Sdk.Models.ShadowTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ForegroundHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TagType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("unique_shadow_tag_name");

                    b.ToTable("ShadowTag", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Cache.CacheImg", b =>
                {
                    b.HasOne("ShadowViewer.Plugin.Local.Entities.ComicNode", null)
                        .WithMany()
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Entities.ComicChapter", b =>
                {
                    b.HasOne("ShadowViewer.Plugin.Local.Entities.ComicNode", null)
                        .WithMany()
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Entities.ComicDetail", b =>
                {
                    b.HasOne("ShadowViewer.Plugin.Local.Entities.ComicNode", null)
                        .WithOne("ComicDetail")
                        .HasForeignKey("ShadowViewer.Plugin.Local.Entities.ComicDetail", "ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Entities.ComicNode", b =>
                {
                    b.HasOne("ShadowViewer.Plugin.Local.Entities.SourcePluginData", "SourcePluginData")
                        .WithMany()
                        .HasForeignKey("SourcePluginDataId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SourcePluginData");
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Entities.ComicPicture", b =>
                {
                    b.HasOne("ShadowViewer.Plugin.Local.Entities.ComicChapter", null)
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShadowViewer.Plugin.Local.Entities.ComicNode", null)
                        .WithMany()
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Models.LocalComicAuthorMapping", b =>
                {
                    b.HasOne("ShadowViewer.Plugin.Local.Models.LocalAuthor", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShadowViewer.Plugin.Local.Entities.ComicDetail", null)
                        .WithMany()
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Models.LocalComicTagMapping", b =>
                {
                    b.HasOne("ShadowViewer.Plugin.Local.Entities.ComicDetail", null)
                        .WithMany()
                        .HasForeignKey("ComicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShadowViewer.Sdk.Models.ShadowTag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Models.LocalReadingRecord", b =>
                {
                    b.HasOne("ShadowViewer.Plugin.Local.Entities.ComicNode", null)
                        .WithOne("ReadingRecord")
                        .HasForeignKey("ShadowViewer.Plugin.Local.Models.LocalReadingRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShadowViewer.Plugin.Local.Entities.ComicNode", b =>
                {
                    b.Navigation("ComicDetail");

                    b.Navigation("ReadingRecord")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
