name: Publish Nuget Packages

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*"

jobs:
  build:
    runs-on: windows-latest
    env:
      Solution_Name: ShadowViewer.Plugin.Local
    steps:
      - uses: mickem/clean-after-action@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            9.0.x
      
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Create NugetPackages
        run: |
          cd ../..
          mkdir NugetPackages

      - name: Build Packages
        run: |
          dotnet restore $env:Solution_Name/$env:Solution_Name.csproj
          dotnet build $env:Solution_Name/$env:Solution_Name.csproj -p:Configuration=Release
      - name: Push package to Nuget registry
        run: |
          cd ../../NugetPackages
          ls
          dotnet nuget push "*.nupkg" -s "https://api.nuget.org/v3/index.json" -k $env:NUGET_KEY --skip-duplicate        
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
